export const gridworldClerkAppearance = {
  variables: {
    borderRadius: "6px",
    colorBackground: "#ffffff",
    colorDanger: "#b00020",
    colorInputBackground: "#ffffff",
    colorInputText: "#111111",
    colorPrimary: "#708090",
    colorText: "#111111",
    colorTextSecondary: "#555555",
    fontFamily: "var(--font-goga), sans-serif",
  },
  elements: {
    rootBox: "gridworld-clerk-root",
    cardBox: "gridworld-clerk-card-box",
    card: "gridworld-clerk-card",
    headerTitle: "gridworld-clerk-title",
    headerSubtitle: "gridworld-clerk-subtitle",
    socialButtonsBlockButton: "gridworld-clerk-social-button",
    dividerLine: "gridworld-clerk-divider-line",
    dividerText: "gridworld-clerk-divider-text",
    formFieldLabel: "gridworld-clerk-label",
    formFieldInput: "gridworld-clerk-input",
    formButtonPrimary: "gridworld-clerk-primary-button",
    footer: "gridworld-clerk-footer",
    footerActionText: "gridworld-clerk-footer-text",
    footerActionLink: "gridworld-clerk-footer-link",
    identityPreview: "gridworld-clerk-identity-preview",
    formResendCodeLink: "gridworld-clerk-link",
    backLink: "gridworld-clerk-link",
  },
};
